import Head from 'next/head'

//Logical components
import Banner from '../../components/banner';
import Explorer from '../../components/explorer/explorer';
import React from 'react';

import {Container} from '../../styles/pageStyles'
import ToolBar from '../../components/toolbar';


export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <ToolBar/>
        <Banner/>
        <Explorer/>
        ref
      </Container>
    </>
  )
}

