import Head from 'next/head'

//Logical components
import React from 'react';

import ContractInfo from '../../components/pages/about/contractInfo';

import {Bottom, Container} from '../../styles/pageStyles'

import Header from '../../components/global/header';

//TODO ADD DEV WALLET TO AUTO PAY 2% FUNDRAISER FEE


export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Header/>
        <ContractInfo/>
        <Bottom>___</Bottom>
      </Container>
    </>
  )
}
