import Head from 'next/head'
import styled from 'styled-components';
import {colors} from '../styles/colors';
import Link from 'next/link';

//Logical components

//Context
import ConnectionProvider from '../context/connectionContext';

export default function FourOFour() {
  return (
    <ConnectionProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Warning>
            <p>404: How did you get here?</p>
            <h1>THIS PAGE HAS NOTHING TO OFFER.</h1>
            <Link href="/">GO BACK HOME</Link>
        </Warning>
      </Container>
    </ConnectionProvider>
  )
}



const Container = styled.div`

    width: auto;
    height: auto;
    background: ${colors.one} ;
    display: block;
    padding: 10px;
    height: 100vh;
    max-height: 100vh;
    padding: 15px;

    display: grid;
    grid-gap: 25px;

    justify-content: center;
    align-items: center;
`

const Warning = styled.div`
    text-align: center;

    a{
        color: ${colors.seven};

        :hover{
            font-weight: bold;
        }
    }
    
`