import Head from 'next/head'
import styled from 'styled-components';
import {colors} from '../styles/colors';

//Logical components
import Banner from '../components/banner/banner';
import Explorer from '../components/explorer/explorer';

//Context
import ConnectionProvider from '../context/connectionContext';

export default function Home() {
  return (
    <ConnectionProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Banner/>
        <Explorer/>
      </Container>
    </ConnectionProvider>
  )
}



const Container = styled.div`

    width: auto;
    height: auto;
    background: ${colors.one} ;
    display: block;
    padding: 10px;
    height: 100vh;
    max-height: 100vh;
    padding: 15px;

    display: grid;
    grid-template-rows: auto auto 1fr;
    grid-gap: 25px;
`