import Head from 'next/head'

//Logical components
import Banner from '../components/banner';
import Explorer from '../components/explorer/explorer';
import React from 'react';

//styled-components
import {Container} from '../styles/pageStyles'
import ToolBar from '../components/toolbar';
 
export default function New() {

  //DISABLE ROUTE WHEN NOT LOGGED IN

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <ToolBar/>
        <Banner/>
        <Explorer/>
        NEW
      </Container>
    </>
  )
}



