import Head from 'next/head'

//Logical components
import Banner from '../components/banner';
import Explorer from '../components/explorer/explorer';
import React from 'react';

//styled-components
import {Container} from '../styles/pageStyles'

//ROUTE AUTH HOC
import withAuth from '../components/hoc/withAuth';
 
const Profile = () => {



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Banner/>
        <Explorer/>
        PROFILE
      </Container>
    </>
  )
}


export default withAuth(Profile);


