import Head from 'next/head'
import {useRouter} from 'next/router';

//Logical components
import Banner from '../components/banner';
import Explorer from '../components/explorer/explorer';
import React from 'react';

//context
import {ConnectionContext} from '../context/connectionContext';


//styled-components
import {Container} from '../styles/pageStyles'
import ToolBar from '../components/toolbar';
import { UserContext } from '../context/userContext';

 
const Profile = () => {

  const {isConnected} = React.useContext(ConnectionContext);
  const {userData} = React.useContext(UserContext);
  const Router = useRouter()

  React.useEffect(() => {
    if(!isConnected || userData === undefined){
      Router.replace('/');
    }
  }, [isConnected, userData])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <ToolBar/>
        <Banner/>
        <Explorer/>
          {userData !== undefined ? userData.walletAddress : ""}
      </Container>
    </>
  )
}


export default Profile;


